# Generated by Django 6.0.7 on 2026-08-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Board Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BoardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('board_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='question_bank.boardclass')),
            ],
            options={
                'ordering': ['board_class', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='question_bank.boardsubject')),
            ],
            options={
                'ordering': ['subject', 'chapter_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BoardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='question_bank.boardchapter')),
            ],
            options={
                'ordering': ['chapter', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BoardSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='question_bank.boardtopic')),
            ],
            options={
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='question_bank.competitiveexam')),
            ],
            options={
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompetitiveSubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='question_bank.competitivemodule')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_flow', models.CharField(choices=[('board', 'Board Type'), ('competitive', 'Competitive Type')], default='board', max_length=20)),
                ('question_text', models.TextField(blank=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('option_a', models.CharField(blank=True, max_length=255)),
                ('option_a_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('option_b', models.CharField(blank=True, max_length=255)),
                ('option_b_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('option_c', models.CharField(blank=True, max_length=255)),
                ('option_c_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('option_d', models.CharField(blank=True, max_length=255)),
                ('option_d_image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.boardsubtopic')),
                ('competitive_submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_bank.competitivesubmodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
