# Generated by Django 6.0.7 on 2026-08-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('institutions', '0001_initial'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutionadminprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='institutionadminprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, to='question_bank.boardclass'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, to='question_bank.boardsubject'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='institutionadminprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institutionadminprofile',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_type',
            field=models.CharField(choices=[('institutional', 'Institutional'), ('independent', 'Independent')], default='independent', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institutions.institution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('institution_admin', 'Institution Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('content_team', 'Content Team')], default='student', max_length=20),
        ),
    ]
