# Generated by Django 6.0.7 on 2026-08-30 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_institutionadminprofile_options_and_more'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assessment_flow',
            field=models.CharField(choices=[('board', 'Board Exam'), ('competitive', 'Competitive Exam')], default='board', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.boardclass'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.boardsubject'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='competitive_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.competitiveexam'),
        ),
    ]
