# Generated by Django 6.0.7 on 2026-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_assessment_flow_and_more'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='assigned_class',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='assigned_subject',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='competitive_exam',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, to='question_bank.boardclass'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, to='question_bank.boardsubject'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='competitive_exams',
            field=models.ManyToManyField(blank=True, to='question_bank.competitiveexam'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='assessment_flow',
            field=models.CharField(choices=[('board', 'Board Exam Only'), ('competitive', 'Competitive Exam Only'), ('both', 'Both (Board & Competitive)')], default='board', max_length=20),
        ),
    ]
