# Generated by Django 6.0.7 on 2026-08-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='board_class',
            field=models.CharField(blank=True, help_text='e.g., 9th, 10th, 1st Year, 2nd Year', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('board', 'Board Class'), ('competitive', 'Competitive Exam')], default='board', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='competitive_exam',
            field=models.CharField(blank=True, help_text='e.g., PPSC Fisheries, CSS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='Biology', help_text='e.g., Biology, Mathematics', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentquizscore',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
