# Generated by Django 6.0.7 on 2026-08-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_board_class_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('board', 'Board Class'), ('competitive', 'Competitive Exam')], default='board', max_length=20)),
                ('board_class', models.CharField(blank=True, help_text='e.g., Class 9th', max_length=100, null=True)),
                ('subject', models.CharField(default='Biology', help_text='e.g., Biology', max_length=100)),
                ('competitive_exam', models.CharField(blank=True, help_text='e.g., ISSB', max_length=100, null=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('short', 'Short Answer'), ('essay', 'Essay / Long Question')], default='mcq', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('text', models.TextField(help_text='The main question statement.')),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, help_text="Enter 'A', 'B', 'C', or 'D'", max_length=1, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('category', 'board_class', 'subject', 'competitive_exam')},
        ),
        migrations.AlterField(
            model_name='course',
            name='board_class',
            field=models.CharField(blank=True, help_text='e.g., Class 9th, Class 10th', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='competitive_exam',
            field=models.CharField(blank=True, help_text='e.g., ISSB, PPSC Fisheries', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='Biology', help_text='e.g., Biology, Mathematics', max_length=100),
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
