# Generated by Django 6.0.7 on 2026-08-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_question_alter_lessonprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='board_class',
            field=models.CharField(blank=True, help_text='e.g., Class 9th', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='competitive_exam',
            field=models.CharField(blank=True, help_text='e.g., ISSB', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='Biology', help_text='e.g., Biology', max_length=100),
        ),
    ]
