# Generated by Django 6.0.7 on 2026-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_unique_together_question_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentquizscore',
            name='course',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='course_title',
            field=models.CharField(default='Biology', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentquizscore',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
