# Generated by Django 6.0.7 on 2026-08-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lessonprogress_course_remove_question_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('board', 'Board Class'), ('competitive', 'Competitive Exam')], default='board', max_length=20)),
                ('board_class', models.CharField(blank=True, help_text='e.g., Class 9th', max_length=100, null=True)),
                ('subject', models.CharField(default='Biology', help_text='e.g., Biology', max_length=100)),
                ('competitive_exam', models.CharField(blank=True, help_text='e.g., ISSB', max_length=100, null=True)),
                ('title', models.CharField(help_text='Course Display Title, e.g., Class 9th Biology Complete Course', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson_title',
        ),
        migrations.RemoveField(
            model_name='studentquizscore',
            name='course_title',
        ),
        migrations.AlterField(
            model_name='question',
            name='board_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='competitive_exam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Biology', max_length=100),
        ),
        migrations.AddField(
            model_name='studentquizscore',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='courses.course'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title', max_length=200)),
                ('sequence_order', models.PositiveIntegerField(default=1, help_text='Order in which videos appear in sequence')),
                ('video_url', models.URLField(help_text='YouTube or video streaming URL')),
                ('content_notes', models.TextField(blank=True, help_text='Optional reading notes or summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson'),
        ),
    ]
