# Generated by Django 6.0.7 on 2026-08-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_remove_lessonprogress_course_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='board_class',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='competitive_exam',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Course Title, e.g., Complete Biology Video Series', max_length=200),
        ),
    ]
