# Generated by Django 6.0.7 on 2026-08-31 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_board_class_remove_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('board', 'Board Class'), ('competitive', 'Competitive Exam')], default='board', max_length=20)),
                ('board_class', models.CharField(blank=True, help_text='Must match Question Bank Board Class, e.g., Class 9th', max_length=100, null=True)),
                ('competitive_exam', models.CharField(blank=True, help_text='Must match Question Bank Exam, e.g., ISSB', max_length=100, null=True)),
                ('subject', models.CharField(default='Biology', help_text='Must match Question Bank Subject/Chapter', max_length=100)),
                ('title', models.CharField(help_text='Lesson title, e.g., Introduction to Cell Division', max_length=200)),
                ('sequence_order', models.PositiveIntegerField(default=1, help_text='Playback sequence order')),
                ('video_url', models.URLField(help_text='YouTube video streaming URL')),
                ('content_notes', models.TextField(blank=True, help_text='Optional reading notes or summary', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'board_class', 'competitive_exam', 'subject', 'sequence_order'],
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentquizscore',
            name='course',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.RemoveField(
            model_name='studentquizscore',
            name='student',
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.videolesson'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='StudentQuizScore',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
