# Generated by Django 6.0.7 on 2026-08-31 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_videolesson_remove_lesson_course_and_more'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='question_bank.question'),
        ),
        migrations.DeleteModel(
            name='VideoLesson',
        ),
    ]
