# Generated by Django 6.0.7 on 2026-08-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Bank transaction ID or receipt number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Uploaded screenshot of the payment', null=True, upload_to='receipts/'),
        ),
    ]
