# Generated by Django 6.0.7 on 2026-08-31 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={},
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='passed',
            new_name='is_passed',
        ),
        migrations.RenameField(
            model_name='examattempt',
            old_name='started_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='board_subtopic',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='competitive_submodule',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_practice',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='examattempt',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_class_wide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_percentage',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_practice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_retest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duration in minutes (Defaults to 30 seconds per question)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('official', 'Official Institutional Exam'), ('practice', 'Practice / Independent Exam')], default='practice', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RetestPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for_entire_class', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_permissions', to='examinations.exam')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_retests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_retests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=10, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examinations.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.question')),
            ],
        ),
        migrations.DeleteModel(
            name='AttemptAnswer',
        ),
    ]
