# Generated by Django 6.0.7 on 2026-08-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_alter_exam_options_alter_examattempt_options_and_more'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='board_or_competitive',
            field=models.CharField(blank=True, help_text='e.g., FBISE, PPSC, MDCAT, FSc Part 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(blank=True, help_text='e.g., Biology, Zoology', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.CharField(blank=True, help_text='Specific chapter or topic filter (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', to='question_bank.question'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=10, help_text='Number of questions to pull randomly if not manually selected'),
        ),
    ]
