# Generated by Django 6.0.7 on 2026-08-31 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_remove_exam_board_or_competitive_remove_exam_subject_and_more'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assessment_flow',
            field=models.CharField(choices=[('board', 'Board System (Academic)'), ('competitive', 'Competitive System')], default='board', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='board_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_subject_exams', to='question_bank.boardsubject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='board_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_topic_exams', to='question_bank.boardtopic'),
        ),
        migrations.AddField(
            model_name='exam',
            name='competitive_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitive_module_exams', to='question_bank.competitivemodule'),
        ),
        migrations.AddField(
            model_name='exam',
            name='scope_level',
            field=models.CharField(choices=[('subject', 'Complete Subject'), ('topic', 'Complete Topic'), ('subtopic', 'Specific Subtopic')], default='subtopic', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='board_subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_subtopic_exams', to='question_bank.boardsubtopic'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='competitive_submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitive_submodule_exams', to='question_bank.competitivesubmodule'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
