# Generated by Django 6.0.7 on 2026-08-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0005_exam_assessment_flow_exam_board_subject_and_more'),
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='retestpermission',
            old_name='created_at',
            new_name='granted_at',
        ),
        migrations.RemoveField(
            model_name='retestpermission',
            name='student',
        ),
        migrations.AlterField(
            model_name='exam',
            name='assessment_flow',
            field=models.CharField(choices=[('board', 'Board System'), ('competitive', 'Competitive System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='board_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_exams', to='question_bank.boardsubject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='board_subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopic_exams', to='question_bank.boardsubtopic'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='board_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_exams', to='question_bank.boardtopic'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='competitive_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitive_exams_module', to='question_bank.competitivemodule'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='competitive_submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitive_exams_submodule', to='question_bank.competitivesubmodule'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final'), ('practice', 'Practice')], default='quiz', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='scope_level',
            field=models.CharField(choices=[('subject', 'Subject / Module Level'), ('topic', 'Topic Level'), ('subtopic', 'Subtopic / Submodule Level')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='retestpermission',
            name='granted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retestpermission',
            name='is_for_entire_class',
            field=models.BooleanField(default=True),
        ),
    ]
