# Generated by Django 6.0.7 on 2026-09-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0006_rename_created_at_retestpermission_granted_at_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_exams', to='institutions.institution'),
        ),
    ]
